### ISSUE TITLE
Optimized discrete Laplace sampling

### ISSUE THREAD

**Issue by jtristan** [leanprover/SampCert#15]
The Discrete laplace sampler is implemented in a naive way and its sampling complexity grows linearly with the privacy budget. This is good for a small privacy budget, but there's is a better optimized implementation when it grows. 
The current implementation uses function `DiscreteLaplaceSampleLoop`, and we should also use the optimized version `DiscreteLaplaceSampleLoop'` for large budgets. The optimized algorithm is described [here](https://arxiv.org/abs/2004.00010), in Algorithm 2, page 32. It requires to verify Fact 35.

**Comment by mjdemedeiros** [comment]
Closed by #37
